version: 2
jobs:
  build:
    working_directory: ~/collapsible-appbar
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: yarn install
      - run:
          command: |
            yarn run test